### ISSUE TITLE
Would you be able to add Sonic 3 in the collection by taking the .rsdk from Origins (easy to get, i could give it to you) or with Sonic 3 AIR?

### ISSUE THREAD

**Issue by yoiryosaturn** [Xeeynamo/sonic-hybrid-rsdk#1]
Yeah I don't really feel like buying Sonic Origins lmao (I got the .rsdk of Sonic 3 thanks to someone who gave a link to the uncracked game.

**Comment by Xeeynamo** [comment]
It is not possible: Sonic 3 uses an updated version of RSDK that is incompatible with RSDKv4.

**Comment by yoiryosaturn** [comment]
Aw

**Comment by charlieduzstuf** [comment]
Tried v5u (which is what origins uses)?
Plus u can intergrate the sonic unison launcher to run sonic 3 air with the hybrid rsdk

**Comment by charlieduzstuf** [comment]
Sooooo anyway, gues who forked this repo specifically to add 3 air support, lol

**Comment by yoiryosaturn** [comment]
> Sooooo anyway, gues who forked this repo specifically to add 3 air support, lol

ah cool

**Comment by charlieduzstuf** [comment]
Yep, if u wanna help ill add u
