### ISSUE TITLE
Latest commit / PR broke the application.

### ISSUE THREAD

**Issue by LittlePlanetCD** [Xeeynamo/sonic-hybrid-rsdk#6]
So uh...

the user who used ChatGPT to "code" basically broke the program in more ways than one.

i'd advise looking at the errors the current commit generates.

**Comment by CCIGAMES** [comment]
but thats just my understanding, sorry for the problems it caused

**Comment by charlieduzstuf** [comment]
also me and a guy called MarioMastr#5301 are gonna fix it with maybe 3 air support

**Comment by Xeeynamo** [comment]
> So uh...
> 
> the user who used ChatGPT to "code" basically broke the program in more ways than one.
> 
> i'd advise looking at the errors the current commit generates.

Thanks for letting me know. I am temporarily reverting that commit
